In [68]:
import numpy as np
import matplotlib.pyplot as plt

In [20]:
A=np.mat([[3,-1],
            [1,0]])
A

matrix([[ 3, -1],
        [ 1,  0]])

In [21]:
B=np.mat([[-7,2],
            [3,5]])
B

matrix([[-7,  2],
        [ 3,  5]])

# 矩阵的加和减

In [22]:
A+B

matrix([[-4,  1],
        [ 4,  5]])

In [23]:
np.mat([[3+-7,-1+2],
          [1+3,0+5]])

array([[-4,  1],
       [ 4,  5]])

In [24]:
A-B

matrix([[10, -3],
        [-2, -5]])

# 矩阵的乘和除

In [32]:
A=np.mat([[2,-3],
           [7,5]])
B=np.mat([[10,-8],
           [12,-2]])

In [33]:
# A*B
np.matrix([
    [2*10+-3*12,2*-8+-3*-2],
    [7*10+5*12,7*-8+5*-2]])

matrix([[-16, -10],
        [130, -66]])

In [34]:
A*B

matrix([[-16, -10],
        [130, -66]])

In [35]:
# B*A
np.mat([[10*2+-8*7,10*-3+-8*5],
          [12*2+-2*7,12*-3+-2*5]])

matrix([[-36, -70],
        [ 10, -46]])

In [36]:
B*A

matrix([[-36, -70],
        [ 10, -46]])

In [40]:
A=np.mat('3 1 2;-2 0 5')
B=np.mat('-1 3;0 5;2 5')

In [44]:
A

matrix([[ 3,  1,  2],
        [-2,  0,  5]])

In [45]:
B

matrix([[-1,  3],
        [ 0,  5],
        [ 2,  5]])

In [48]:
# A*B
np.mat([[3*-1+1*0+2*2,3*3+1*5+2*5],
[-2*-1+0*0+5*2,-2*3+0*5+5*5]])

matrix([[ 1, 24],
        [12, 19]])

In [49]:
A*B

matrix([[ 1, 24],
        [12, 19]])

In [51]:
# B*A
np.mat([[-1*3+3*-2,-1*1+3*0,-1*2+3*5],
[0*3+5*-2,0*1+5*0,0*2+5*5],
[2*3+5*-2,2*1+5*0,2*2+5*5]])

matrix([[ -9,  -1,  13],
        [-10,   0,  25],
        [ -4,   2,  29]])

In [52]:
B*A

matrix([[ -9,  -1,  13],
        [-10,   0,  25],
        [ -4,   2,  29]])

# 矩阵的逆

In [55]:
A=np.mat([['a','b'],
         ['c','d']])

In [56]:
A

matrix([['a', 'b'],
        ['c', 'd']], dtype='<U1')

## A的逆矩阵计算：

$$A^{-1}=\frac{1}{ad-bc}\begin{bmatrix}d,-b\\-c,a\\\end{bmatrix}$$

# A的行列式：
$$|A|=ad-bc$$

In [62]:
B=np.mat([[3,-4],[2,-5]])
B

matrix([[ 3, -4],
        [ 2, -5]])

In [67]:
BB=(1/((3*-5)-(2*-4)))*np.mat([[-5,4],[-2,3]])
BB

matrix([[ 0.71428571, -0.57142857],
        [ 0.28571429, -0.42857143]])

In [65]:
BB*B

matrix([[1.00000000e+00, 2.22044605e-16],
        [0.00000000e+00, 1.00000000e+00]])

In [66]:
np.linalg.inv(B)

matrix([[ 0.71428571, -0.57142857],
        [ 0.28571429, -0.42857143]])

# 高斯消去法

原始矩阵
$$\begin{bmatrix}1,0,1\\0,2,1\\1,1,1\\\end{bmatrix}$$

画出单位矩阵：
$$\begin{bmatrix}1,0,1\\0,2,1\\1,1,1\\\end{bmatrix}|\begin{bmatrix}1,0,0\\0,1,0\\0,0,1\\\end{bmatrix}$$

对同行进行加减，或者替换、交换、以及两行之间相加减得到的结果替换某一行。

1.第三行减去第一行：
$$\begin{bmatrix}1,0,1\\0,2,1\\0,1,0\\\end{bmatrix}|\begin{bmatrix}1,0,0\\0,1,0\\-1,0,1\\\end{bmatrix}$$

2.第三行和第二行交换位置
$$\begin{bmatrix}1,0,1\\0,1,0\\0,2,1\\\end{bmatrix}|\begin{bmatrix}1,0,0\\-1,0,1\\0,1,0\\\end{bmatrix}$$

3.第三行减去第二行得到的结果替换第三行：
$$\begin{bmatrix}1,0,1\\0,1,0\\0,0,1\\\end{bmatrix}|\begin{bmatrix}1,0,0\\-1,0,1\\2,1,-2\\\end{bmatrix}$$

4.第一行减去第三行得到的结果替换第一行：
$$\begin{bmatrix}1,0,0\\0,1,0\\0,0,1\\\end{bmatrix}|\begin{bmatrix}-1,-1,2\\-1,0,1\\2,1,-2\\\end{bmatrix}$$

### 最终得到的右边的矩阵即为原始矩阵的逆

## 矩阵法求解方程组

$$3x+2y=7$$
$$-6x+6y=6$$

转换成矩阵就是：
$$\underbrace{\begin{bmatrix}3,2\\-6,6\\\end{bmatrix}}_{A}\underbrace{\begin{bmatrix}x\\y\\\end{bmatrix}}_{B}=\underbrace{\begin{bmatrix}7\\6\\\end{bmatrix}}_{C}$$

两边同时乘以矩阵A的逆：
$$A^{-1}AB=A^{-1}C$$
$$\Downarrow$$
$$IB=A^{-1}C$$
$$\Downarrow$$
$$B=A^{-1}C$$

In [69]:
B=np.linalg.inv(np.mat([[3,2],[-6,6]]))*np.mat("7;6")

In [70]:
B

matrix([[1.],
        [2.]])

## 奇异矩阵

首先，如果一个矩阵A存在另外一个矩阵B使得：
$$AB=BA=I$$
那么矩阵A是可逆的，称为非奇异矩阵。

那么找不到上述的矩阵B，则A称为奇异矩阵。也就是A不可逆

依据上述求逆方法，当矩阵A的项列式：
$$|A|=ad-bc=0$$
则矩阵A不可逆

# 三元线性方程

求解方法，初中数学即可。